apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- echo-canary-deploy.yaml
- echo-stable-deploy.yaml
- echo-canary-svc.yaml
- echo-stable-svc.yaml
- ing-canary.yaml
- ing-stable.yaml
- hpa.yaml
- vpa-helmrelease.yaml
- vpa-helmrepo.yaml
- vpa.yaml